INSERT INTO ROLE(ROLE) VALUES ('ROLE_ADMIN');
INSERT INTO ROLE(ROLE) VALUES ('ROLE_PROFESSOR');
INSERT INTO ROLE(ROLE) VALUES ('ROLE_USER');

INSERT INTO FILE_DATA(NAME, TYPE, FILE_PATH) VALUES ('profile.png', 'png', 'C:\Users\paulo\IdeaProjects\my\saper-back-end\files\1\thalyson.png');
INSERT INTO FILE_DATA(NAME, TYPE, FILE_PATH) VALUES ('profile.png', 'png', 'C:\Users\paulo\IdeaProjects\my\saper-back-end\files\2\saulo.png');
INSERT INTO FILE_DATA(NAME, TYPE, FILE_PATH) VALUES ('profile.png', 'png', 'C:\Users\paulo\IdeaProjects\my\saper-back-end\files\3\profile.png');
INSERT INTO FILE_DATA(NAME, TYPE, FILE_PATH) VALUES ('profile.png', 'png', 'C:\Users\paulo\IdeaProjects\my\saper-back-end\files\4\paulo.png');

INSERT INTO CLIENT(NAME, LOGIN, PASSWORD, PROFILE_IMAGE_ID) VALUES ('Thalyson','thalyson','$2a$10$224Y56.QHRu.7XDU9CwlG.ZMfVWUWm0YBvslnF.hdmsKXTJlgb/YK', 1);
INSERT INTO STUDENT(PAID, REGISTRATION, CLIENT_ID) VALUES (0, '20220001', 1);
INSERT INTO CLIENT_ROLE(CLIENT_ID, ROLE_ID) VALUES (1, 1);

INSERT INTO CLIENT(NAME, LOGIN, PASSWORD, PROFILE_IMAGE_ID) VALUES ('Saulo','saulo', '$2a$10$224Y56.QHRu.7XDU9CwlG.ZMfVWUWm0YBvslnF.hdmsKXTJlgb/YK', 2);
INSERT INTO STUDENT(PAID, REGISTRATION, CLIENT_ID) VALUES (0, '20220002', 2);
INSERT INTO CLIENT_ROLE(CLIENT_ID, ROLE_ID) VALUES (2, 2);

INSERT INTO CLIENT(NAME, LOGIN, PASSWORD, PROFILE_IMAGE_ID) VALUES ('Adriano', 'adriano', '$2a$10$224Y56.QHRu.7XDU9CwlG.ZMfVWUWm0YBvslnF.hdmsKXTJlgb/YK', 3);
INSERT INTO STUDENT(PAID, REGISTRATION, CLIENT_ID) VALUES (0, '20220003', 3);
INSERT INTO CLIENT_ROLE(CLIENT_ID, ROLE_ID) VALUES (3, 3);

INSERT INTO CLIENT(NAME, LOGIN, PASSWORD, PROFILE_IMAGE_ID) VALUES ('Paulo', 'paulo', '$2a$10$224Y56.QHRu.7XDU9CwlG.ZMfVWUWm0YBvslnF.hdmsKXTJlgb/YK', 4);
INSERT INTO PROFESSOR(REGISTRATION, CLIENT_ID) VALUES ('20220004', 4);
INSERT INTO CLIENT_ROLE(CLIENT_ID, ROLE_ID) VALUES (4,2);

INSERT INTO BOX(CAPACITY, CREATED_BY, NAME) VALUES (1,'Thalyson','BinoBox');
INSERT INTO BOX(CAPACITY, CREATED_BY, NAME) VALUES (2,'Thalyson','BinoBox Fortaleza');
INSERT INTO BOX(CAPACITY, CREATED_BY, NAME) VALUES (50,'Saulo','SaBox');
INSERT INTO BOX(CAPACITY, CREATED_BY, NAME) VALUES (10,'Paulo','SaBox');

INSERT INTO TEAM(SCHEDULE, BOX_ID, PROFESSOR_ID) VALUES ('246_19', 1, 1);
INSERT INTO TEAM(SCHEDULE, BOX_ID, PROFESSOR_ID) VALUES ('35_09', 2, 1);
INSERT INTO TEAM(SCHEDULE, BOX_ID, PROFESSOR_ID) VALUES ('246', 4, 1);

INSERT INTO ENROLLMENT(STUDENT_ID, TEAM_ID) VALUES (2, 1);
INSERT INTO ENROLLMENT(STUDENT_ID, TEAM_ID) VALUES (2, 2);
